# Jykell configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'en-uk'

# Website info
name: 'Digital Data Streams Blog'
description: 'Ideas, thoughts, and reflections about Information Systems'

# Author's info
author: 'Digital Data Streams Lab'
# edit 'categories' in the front matter of every post to match this username
nickname: 'ddslab'
bio: 'The mission of the DDS Lab is to be at the forefront of knowledge and understanding of DDS - from their generation and processing to their productive and strategic use.'
location: 'Louisiana State University, USA'
# url: 'https://zampolli75.github.io/introduction_to_IS_website/'
url: 'http://blog.ddslab.org'
image: 'assets/images/casper.png'

short_url: 'blog.ddslab.org'
google_analytics: UA-69281367-1
disqus: username
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /

# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag


# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: false
lsi: false
username: zampolli75
repo: introduction_to_is_website
branch: master
relative_source: ../introduction_to_is_website/
destination: ../website/
production_url:  https://github.com/zampolli75/introduction_to_is_website/
source_url:      https://github.com/zampolli75/introduction_to_is_website/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
